apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgAgqShzx6+wPahpUh7xnwd29l+iL4xxl4z6+N6Nj3TeY5C0uiKNPmyzVZN33TD4h71QZOCyM4Lq1W0R4rOtkCd+OBpwFDVlgJ3g8b5W2fP0m8vhst6821psG7WJ1iPu1XTNdx6vtaZyI4vYF4ttG1AdvUaJAGkOybbi+S8eJnNC5qV8JGlJZXL0qajnM5klYVjXn8pQpBjsg+qLvLfgX/KImDGQKtNQjI70lFSZNbIPk+3ejuqobSKLj1islVe1I4hWGmmpiqv5RRtserNL8tk1rtf/9M7gTT0MvSxsrAFdk5c2IC9OaETIKzmzN1Dzm9iRimabCPMeAJmut3Wx5m+mXHRju/OR3LhkIsm39njmu09lZYD1cit9hO1UnD/bu3d/l05j/wnyRh1BCuWWFur05Ttt9FZ6bkT4k8mE18WKvvfkBnAu16JaX4j4aoadbvxtBdJDNDTtwjbdou93LJMX51267QSGRDRaQHFp4IwXnGZERWNA22AnTUcTSBDtK/kpqlBwVdFMbu87WytgqUXQBbPdIQ/Zx68vHjEjnEZKpApGR2kniEVR3t0U1bDjv1ilwc3Ein6xsGRzr6bfSYtM/Wb0l4JB2VZVuzCn80s9gaVqumPkaxRjADUfl3TpWYHPTmguzqT+k2OKufBcxCL6zP+vLLFEWkx9KNhrpuw1owtf3oVBBXsQZR/B5xv/Rs9WqQoiucqBPA==
    DB_USER: AgCqjBr6pO0jVKZKo3SMEijbi6IiaLH7SWlrVGlPfcOGlLGKz/ww0Qwdzf5+soCXQM41BXO3I2xVDRSB5LRF7JrsSdWni/YBA+ZFt+R8mKxJzHu8RNqua3w8mfZDEkgXEsrk0PNpZ7wb3P1AoCyjn0/A3/DBafhmhG5NWuafOlCBg8Ce+aOuXow92+j9zQZAyPrxL1fca0HrMexJbfmCciGa0BCfuAlfEKtFIzl/96O1Ns1E2wn7gSHR+lnDF9rkBWwDK0A/SGeWvWN9aOuIZTRVUzkX2j+df9D8tjv1+TwGe58i/G8Ty8DfdvPFMn8HauZQ0mJLyQqxNGSHqV0npSjquNl7wg5fXT1AkU47b+rIlqwm49ZrACb6f/AB4erF8df7boRhhzWhGbG5F4IGMGSpfx7OyFkiVWOxU0yX4CCCi6aWn4y9yBWHsT4rXwWGITYQW+D9ufPgGLo1oDHANLdN+BXIOHi9YSeBOMnN87mAKhb8ke2Almk1qwQjAep+lXy2DHj7Pc7VJhxCOAr+ZJnZQ1jpfubbo+bWGZUcEEWO4kqZFHzyrkauXi902bbrsY5mGFBquTKwWnyTz81OVwzISEotnERhEkg9HicQUCdXkpLnBElbT1thy5Emg+bYTdAKUGlv6mW9TstRJIXhF3AeNvVnZ8ILFtfFJn5rxXFA6qUkulxwXhaeb6svFbbzOqJm82HnQ3eL7A==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

