apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgB58lPJKsg3/doqsxIyOrVzAndHluK9+2Wxactc5tGC0jsPzaAjRtOGFceb+BtlktwtcDxL0jK9sPrd6XoYgqqW0QIfuaSkwBW+MUcbi3XIhseQCtyBW2zkkQ074Py5bKeMlMXH+FjqD3T2kL6bG9XvT6jz/H7FFV495cr6a7FBM8C7cPIhZVh46YuDgA3mGoA3pyKxxMBfSud2MOpVk6e2lQfvyQ1FPwrDHZqW7srfTIhMK3R/7Mk0cstYPmjOqsFUvkguDPoTEBmFzduw+GGcm1PYldiQdSLuGe4VJii3ECXdCOv/501cerwqIOOv9Wdjp2cKFwmcX+i6DsLChphKb0Zx0v9A0udddPZpndQDx/qkMoZ1PvLoiTEyw2v+e3MqrbjY8mFHw/ZEW4msnSAk8x9utC6YpiOssErQXRJYeDy/kl2EfUjKdddSdrSWyu2A8Yeq/UDtT6S1LNRTRqhcIyNZDCIc72Oqf7415PUztAbEZucE7fdS46HfPtl/cL6JXx+anygq8ULKD49qhQOqs5ij1F+dXJpKF3qYuTby/UiBgb/edRMnOuT+Us8K7gn1AEBPt435fgH9KeIb9ndStTnUwyHh+h3hoklGUr2WVd3b8U95LudRH+g/tAtT/cpR1eFZY4ktVbEQcBlE8LRMnUlAG1hFn15yzMOiwMGq2Rd9bzmuOxDd9Ako9S99K6wkdBvcR+Y4lw==
    DB_USER: AgBTAMxfepbXGzrcY/pAT3u8fj1IGFaf61vSIrk/CymkHlmnLel0lizCuNCAUfibwcCB0YfIkwD1rwqArZ/iLjlEex7EaYpa+VYz+08KPVMJx/QU4GIPkqXF8hU/3n2sE7UPM2bJVj5Yl6qlkJiZivKUho7M1G5V/sXcgHpraoTEKWtBIi06P6qIt8d3AR1nHhcwmLGgcEgeRSE6oGDG6/DlUCI8H95pyV/zqMjdMBPtS8nqHZqbrmyn+x/g9hPFoQGLf6Ov50Potv8ARzvPyUVf5Ai5q/5HrtX0iKCMIn1XxwIZz6EJs6PQrMtE804AWpZzRU1m9HIPE+4eik+MphI/50A0FZ0IrHbTCiWYS7IwpnoDzmkdV0U9A3aoqiraIVX2a0+2zTPeWNEkAJlGskfDgjnqQuwzemGbzKaiweP7ZqbqaxxmjxBHW2okOb+d42Q086UYXXqt4cZcPf3XdLsFYp34y6p41EaypHF2/nU8y7ELf6AqSMeAcpR2rIbkv0A3PyAwo7tAOr9waKlnR4RVK6hboHgtKlywqQM3aZboJAqQXxyKJsd+DDHuKvR3S7sK8Y8OLHycuJQZbNZAOqJwA9qgBl3qeOQOImm2b04k28LkdmiFanx7SVjZJbfTSJLNPe2YBFUqOrN3rVi8k8ds4+ZjVBlsSiy6VzTI+yR/rIDGdJY/8S35JH0zRRTi+DqP151dUZIUaQ==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

