apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgB8QOszp6Tv6WKc2W8OSTUVOeS6awKcy6j88QVMAR3RGz9JPNENvL0/16jYrp7NQ8nE6AgSR6XMQwh2pmVzsSdNwLJjv3s+1/UczuIjilViSXTO9bcGXiXr5jash4tQqGNztCS48A4RjH2EKHUoP1qSvtYIchm98oVuvTRnKi/jWMEzOl3AgX5AQ2lvGwZVvW2I5YPnDZxesIplIwongl/c0ObaD72qw++rPHrNBl1sJRaqLNKVFjASdRb9cIunVCNX99gQVJdO7ARCQs+FCIepwYgQOyLcmbmiT7+GeTXkJm7riNSWpuIUE56NZnM6Ds0qsoTwKDDsJCXWLEBPg+45CBWkr6ie3DOv+LTES9bfbk3jl5NYa1knrZlLnXXDA6e/gGrZkp2lZMfV3Wgxmy+C8/Rn0DYzHrv5TIsOWaJQYx5xYPJt28Fim8RWiG22YmSPWfOQUV2u9SzJNQ6eX9B/DAk1P4TzSAhipvlV1lzaVXLHDzrmu6WcaTcRuB3/jspR6yqOIAVwC8PLotO6SmQssobmlBvOdAU8BGanIY7nqm5+ICypNA7+ZUQbnwdJGCMF3DqfkD7/MpgJKmjznCDzrJT7sNGRFbNuLJ8wbWetqH2Ux6yo8fM8nyfn5lOFHTZ8toFSohk+EKaU8TW76JusgCp1Qv3s//f9t/TrNeUNQkgHrKH9E38vFMq+lD9PmcwW8C0LzPlBwQ==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

